name: renv-install-system-dependencies
description: 'Installs system dependencies from renv.lock file'
inputs:
  path:
    description: 'Path to renv.lock file'
    required: true

runs:
  using: "composite"
  steps:
    - id: query-dependencies
      uses: mlr-org/actions/renv-query-system-dependencies@e3ac0973ff7977a7430d8fed20b8e56dbc49315a

    - run: ${{ steps.query-dependencies.outputs.command }}
      shell: bash

