on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: renv-install-system-dependencies

jobs:
  renv-system-dependencies-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install System Dependencies
        uses: mlr-org/actions/renv-install-system-dependencies@773080b992bfccb9698801f201773c7db91f2b99
        with:
          path: 'renv.lock'